export const FETCH_RECIPES_START = 'FETCH_RECIPES_START'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL'
export const CLEAR_FETCH_RECIPES_ERROR = 'CLEAR_FETCH_RECIPES_ERROR'